name: Release new version HuggingFace Hub

on:
  push:
    tags:
     - '*'

jobs:
  push-to-hf-hub:
    name: Release new version to HuggingFace Hub
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install Requirements
      run: pip install -r requirements/base.rqr

    - name: Install Requirements
      run: pip install isort

    - name: Prepare dataset imports
      run: >-
        bash ./utils/hf/prepare_dataset_imports.sh

    - name: Prepare metric imports
      run: >-
        bash ./utils/hf/prepare_metric_imports.sh

    - name: Push dataset to HuggingFace Hub
      env:
        HUGGINGFACE_HUB_TOKEN: ${{ secrets.UNITXT_HUGGINGFACE_WRITE_TOKEN }}
      run: >-
        python ./utils/hf/prepare_dataset.py

    - name: Push metric to HuggingFace Hub
      env:
        HUGGINGFACE_HUB_TOKEN: ${{ secrets.UNITXT_HUGGINGFACE_WRITE_TOKEN }}
      run: >-
        python ./utils/hf/prepare_metric.py
