name: Run when new branch merged into the main
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    name: Create new tag if needed
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        ref: main

    - name: Create tag and push
      run: >-
        ./utils/create_tag_for_new_version
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_TO_GITHUB_TOKEN }}
